PEOPLE = [
    "Albert Einstein",
    "Marie Curie",
    "Leonardo da Vinci",
    "William Shakespeare",
    "Ada Lovelace",
    "Nikola Tesla",
    "Lionel Messi",
    "Cristiano Ronaldo",
    "Taylor Swift",
    "Frida Kahlo",
    "Isaac Newton",
    "Galileo Galilei",
    "Mahatma Gandhi",
    "Nelson Mandela",
    "Steve Jobs",
    "Alan Turing",
    "Pablo Picasso",
    "Wolfgang Amadeus Mozart",
    "Cleopatra",
    "Joan of Arc",
]

PLACES = [
    "Eiffel Tower",
    "Great Wall of China",
    "Taj Mahal",
    "Grand Canyon",
    "Machu Picchu",
    "Colosseum",
    "Hagia Sophia",
    "Statue of Liberty",
    "Pyramids of Giza",
    "Mount Everest",
    "Sydney Opera House",
    "Niagara Falls",
    "Stonehenge",
    "Angkor Wat",
    "Petra",
    "Golden Gate Bridge",
    "Burj Khalifa",
    "Santorini",
    "Great Barrier Reef",
    "Serengeti",
]
